name: JobSearch
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 
  json_annotation: 
  animated_text_kit: ^4.2.2
  hooks_riverpod: 
  
  flutter_hooks: 
  
  go_router: 
  
  freezed_annotation: 
  
  loader_overlay: 
  
  uuid: 
  
  flutter_svg: 
  
  isar: 
  
  firebase_storage: ^11.2.2 
  
  cloud_firestore: 
  
  firebase_auth: 
  
  firebase_core: 
  auth_buttons: ^1.0.1+4
  flutter_spinkit: ^5.2.0
  shimmer: ^3.0.0
  http: ^0.13.6
  transparent_image: ^2.0.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 
  flutter_launcher_icons: 
  flutter_native_splash: 
  build_runner: 
  freezed: 
  json_serializable: 
  custom_lint:
  riverpod_lint:

    
    

# flutter pub run flutter_launcher_icons
flutter:

  uses-material-design: true

  assets:
    - assets/
    - fonts/

  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-ExtraBold.ttf
        - asset: fonts/Inter-Light.ttf
        - asset: fonts/Inter-ExtraLight.ttf
        - asset: fonts/Inter-Medium.ttf
        - asset: fonts/Inter-SemiBold.ttf
        - asset: fonts/Inter-Thin.ttf
        - asset: fonts/Inter-Black.ttf
        - asset: fonts/Inter-Regular.ttf
        - asset: fonts/Inter-Bold.ttf
  
