// This file is "main.dart"

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'job_model.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'job_model.g.dart';

@freezed
class JobModel with _$JobModel {
  const factory JobModel({
    required String title,
    required String degree, 
    required String jobType,
    required bool isRemote, // man or woman
    required String organization,
    required String minimumQualifications,
    required String preferredQualifications,
    required String responsibilities,
    required String aboutJob,
    required int longitude,
    required int latitude,
    required int salaryPerHour,
    
  }) = _JobModel;

  factory JobModel.fromJson(Map<String, Object?> json) =>
      _$JobModelFromJson(json);
}
