// This file is "main.dart"
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'job_offer_model.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'job_offer_model.g.dart';

@freezed
class JobOfferModel with _$JobOfferModel {
  const factory JobOfferModel({

    required String senderUid, // user id of who sent the offter 
    required String recipientUid, // user id of who received the offer
    required String jobId,
    required dynamic timestampField,
    String? jobOfferId,
    required bool? status, // can be null= unanswered by the recipient, true= accepted, false= rejected

  }) = _JobOfferModel;

  factory JobOfferModel.fromJson(Map<String, Object?> json) =>
      _$JobOfferModelFromJson(json);
}
