// This file is "main.dart"
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'merged_storage_file.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.


@freezed
class MergedStorageFile with _$MergedStorageFile {
  const factory MergedStorageFile({
    required Map<String,String>? customMetadata,
    required Uint8List? rawData,
    required String? downloadUrl,
    
  }) = _MergedStorageFile;

}
