// This file is "main.dart"
import 'package:JobSearch/model/data/application_model.dart';
import 'package:JobSearch/model/data/job_model.dart';
import 'package:JobSearch/model/data/user_model.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'merged_my_applications_model.freezed.dart';


@freezed
class MergedMyApplicationsModel with _$MergedMyApplicationsModel {
  const factory MergedMyApplicationsModel({
    required JobModel jobModel,
    required ApplicationModel applicationModel,
    
    
  }) = _MergedMyApplicationsModel;

}
